"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose -- Django must fail loudly at startup if SECRET_KEY
# isn't set via the environment/.env, rather than silently falling back to a
# value baked into source (this repo used to do exactly that).
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# No raw IPs here on purpose (VPS public IP, internal Multipass VM IPs) --
# only domain names, which aren't sensitive the way raw infra IPs are.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "example.com",
    "flowise.example.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://example.com",
    "https://bot.example.com",
    "https://flowise.example.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'flowise_questionnaire',
    'mcp_server',
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "flowise_questionnaire_db",
        "USER": "flowise_questionnaire_user",
        # No default on purpose -- see SECRET_KEY above for why. Every
        # environment (local dev against the Multipass VM, and the VPS)
        # must set this via its own .env.
        "PASSWORD": config('DB_PASSWORD'),
        # No default on purpose -- was the Multipass VM's raw internal IP.
        "HOST": config('DB_HOST'),
        "PORT": "5432",
        # mcp_server calls the ORM via sync_to_async from a raw ASGI
        # middleware (TokenAuthMiddleware), outside Django's normal view
        # dispatch -- so the request_started/request_finished signals that
        # would otherwise recycle a dead connection never fire there. A
        # connection that goes stale (e.g. Postgres restarts, or it sits
        # idle past the DB's own timeout) then stays stale for every
        # subsequent request on that thread, surfacing as
        # django.db.utils.InterfaceError: connection already closed.
        # CONN_HEALTH_CHECKS pings the connection via ensure_connection()
        # on each use and transparently reopens it if dead, which works
        # here since it's hooked into the connection object itself rather
        # than the request-cycle signals this app bypasses.
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
import os

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/questionnaires/login/"
LOGIN_REDIRECT_URL = "/questionnaires/"
LOGOUT_REDIRECT_URL = "/questionnaires/login/"


# Flowise integration
FLOWISE_BASE_URL = os.getenv(
    "FLOWISE_BASE_URL",
    "http://127.0.0.1:3000",
)

FLOWISE_MODULE_REVIEW_AGENTFLOW_ID = os.getenv(
    "FLOWISE_MODULE_REVIEW_AGENTFLOW_ID",
    "0b6f2811-62fa-40c4-ac35-5f39d1392e4f",
)

FLOWISE_TIMEOUT_SECONDS = int(
    os.getenv("FLOWISE_TIMEOUT_SECONDS", "300")
)

# Flowise interview simulator wording integration
#
# Temporary direct settings for development.
# Flowise is used only to format the respondent-facing question message.
# Django still controls answer validation, code mapping, routing, and graph highlighting.
FLOWISE_INTERVIEW_WORDING_ENABLED = True

FLOWISE_INTERVIEW_WORDING_AGENTFLOW_ID = "efd4ab1f-d1f0-4c15-b7e7-5994072d9916"

FLOWISE_INTERVIEW_WORDING_CACHE_TIMEOUT_SECONDS = 60 * 60 * 24

# MCP server (mcp_server app) -- read-only MCP tools for Colectica questionnaire data,
# served by `manage.py runmcp` as its own standalone process. Used to build the full
# connector URL shown to admins when generating per-person access tokens (see
# mcp_server.models.McpAccessToken.connector_url).
MCP_PUBLIC_BASE_URL = config(
    'MCP_PUBLIC_BASE_URL',
    default='https://mcp.example.com',
)