# Generated by Django 6.0.5 on 2026-05-23 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('uploaded_file', models.FileField(upload_to='flowise_questionnaires/raw_json/')),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowise_questionnaire_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flowise_questionnaire_module',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nodes_json', models.JSONField(blank=True, default=list)),
                ('edges_json', models.JSONField(blank=True, default=list)),
                ('mermaid_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'db_table': 'flowise_questionnaire_graph',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flowise_flow_id', models.CharField(blank=True, max_length=255)),
                ('task_type', models.CharField(choices=[('schema_review', 'Schema review'), ('routing_analysis', 'Routing analysis'), ('test_planning', 'Test planning'), ('synthetic_profile_generation', 'Synthetic profile generation'), ('semantic_validation', 'Semantic validation'), ('report_explanation', 'Report explanation')], max_length=80)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'db_table': 'flowise_agent_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_question', models.CharField(blank=True, max_length=255)),
                ('target_question', models.CharField(max_length=255)),
                ('condition_text', models.TextField(blank=True)),
                ('condition_ast', models.JSONField(blank=True, null=True)),
                ('edge_type', models.CharField(choices=[('sequential', 'Sequential'), ('conditional', 'Conditional'), ('loop', 'Loop'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_edges', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'db_table': 'flowise_routing_edge',
                'ordering': ['module', 'sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('random', 'Random'), ('target_question', 'Target question'), ('full_coverage', 'Full coverage')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('requested_config_json', models.JSONField(blank=True, default=dict)),
                ('coverage_json', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='flowise_questionnaire.questionnairemodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowise_simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flowise_simulation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyntheticProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_json', models.JSONField(blank=True, default=dict)),
                ('seed_answers_json', models.JSONField(blank=True, default=dict)),
                ('target_routes_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synthetic_profiles', to='flowise_questionnaire.agentrun')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_profiles', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'db_table': 'flowise_synthetic_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers_json', models.JSONField(blank=True, default=dict)),
                ('active_path_json', models.JSONField(blank=True, default=list)),
                ('skipped_questions_json', models.JSONField(blank=True, default=list)),
                ('validation_result_json', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='flowise_questionnaire.simulationrun')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_cases', to='flowise_questionnaire.syntheticprofile')),
            ],
            options={
                'db_table': 'flowise_simulation_case',
                'ordering': ['simulation_run', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=30)),
                ('issue_type', models.CharField(max_length=100)),
                ('question_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='flowise_questionnaire.simulationcase')),
            ],
            options={
                'db_table': 'flowise_validation_issue',
                'ordering': ['simulation_case', 'severity', 'question_name'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multi_choice', 'Multi choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('help_text', models.TextField(blank=True)),
                ('interviewer_instruction', models.TextField(blank=True)),
                ('source_identifier', models.CharField(blank=True, max_length=255)),
                ('source_composite_id', models.JSONField(blank=True, null=True)),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_questions', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'db_table': 'flowise_normalized_question',
                'ordering': ['module', 'sequence_index', 'name'],
                'constraints': [models.UniqueConstraint(fields=('module', 'name'), name='flowise_unique_question_per_module')],
            },
        ),
    ]
