# Generated by Django 6.0.5 on 2026-05-24 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='error', max_length=20)),
                ('review_json', models.JSONField(blank=True, default=dict)),
                ('post_validation_json', models.JSONField(blank=True, default=dict)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reviews', to='flowise_questionnaire.questionnairemodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
