# Generated by Django 6.0.5 on 2026-05-29 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0002_moduleaireview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSimulatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], db_index=True, default='active', max_length=20)),
                ('current_question_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('previous_question_name', models.CharField(blank=True, default='', max_length=255)),
                ('answers_json', models.JSONField(blank=True, default=dict, help_text='Internal coded answers keyed by questionnaire variable name.')),
                ('routing_trace_json', models.JSONField(blank=True, default=list, help_text='Deterministic routing trace for debugging and replay.')),
                ('graph_highlight_json', models.JSONField(blank=True, default=dict, help_text='Latest graph highlight payload for frontend synchronization.')),
                ('debug_json', models.JSONField(blank=True, default=dict, help_text='Latest designer/debug information for this simulator session.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_simulator_sessions', to='flowise_questionnaire.questionnairemodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_simulator_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSimulatorTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_index', models.PositiveIntegerField(db_index=True)),
                ('question_name', models.CharField(db_index=True, max_length=255)),
                ('question_text', models.TextField(blank=True, default='')),
                ('selection_mode', models.CharField(blank=True, default='', help_text='single or multiple.', max_length=20)),
                ('shown_options_json', models.JSONField(blank=True, default=list, help_text='A/B/C respondent-facing options shown at this turn.')),
                ('assistant_message', models.TextField(blank=True, default='', help_text='Question message shown to respondent.')),
                ('user_answer_text', models.TextField(blank=True, default='', help_text='Raw respondent input, usually A/B/C letters.')),
                ('user_answer_letters_json', models.JSONField(blank=True, default=list)),
                ('coded_answer_json', models.JSONField(blank=True, default=dict, help_text="Validated internal answer code, e.g. {'BENBASE': [3]}.")),
                ('validation_json', models.JSONField(blank=True, default=dict)),
                ('routing_result_json', models.JSONField(blank=True, default=dict)),
                ('graph_highlight_json', models.JSONField(blank=True, default=dict)),
                ('flowise_request_json', models.JSONField(blank=True, default=dict)),
                ('flowise_response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='flowise_questionnaire.interviewsimulatorsession')),
            ],
            options={
                'ordering': ['session', 'turn_index'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsimulatorsession',
            index=models.Index(fields=['module', 'status'], name='flowise_que_module__5994dd_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsimulatorsession',
            index=models.Index(fields=['user', 'status'], name='flowise_que_user_id_c85cae_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsimulatorsession',
            index=models.Index(fields=['current_question_name'], name='flowise_que_current_7b6bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsimulatorturn',
            index=models.Index(fields=['session', 'turn_index'], name='flowise_que_session_2f191b_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsimulatorturn',
            index=models.Index(fields=['question_name'], name='flowise_que_questio_26dad9_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewsimulatorturn',
            constraint=models.UniqueConstraint(fields=('session', 'turn_index'), name='unique_interview_simulator_turn_per_session'),
        ),
    ]
