# Generated by Django 6.0.5 on 2026-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0003_interviewsimulatorsession_interviewsimulatorturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairemodule',
            name='raw_xml',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnairemodule',
            name='source_format',
            field=models.CharField(choices=[('colectica_json', 'Colectica JSON'), ('forsta_xml', 'Forsta+ XML')], default='colectica_json', max_length=30),
        ),
    ]
