# Generated by Django 6.0.5 on 2026-07-17 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0004_questionnairemodule_raw_xml_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multi_choice', 'Multi choice'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('grid_matrix', 'Grid / Matrix'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='QuestionMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy'), ('manual', 'Manual')], default='fuzzy', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colectica_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colectica_matches', to='flowise_questionnaire.normalizedquestion')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forsta_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forsta_matches', to='flowise_questionnaire.normalizedquestion')),
            ],
            options={
                'db_table': 'flowise_question_match',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='RoutingDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discrepancy_type', models.CharField(choices=[('missing_in_forsta', 'Missing in Forsta+'), ('missing_in_colectica', 'Missing in Colectica'), ('condition_mismatch', 'Condition mismatch'), ('else_branch_only_in_forsta', 'Else branch only in Forsta+')], max_length=40)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colectica_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flowise_questionnaire.routingedge')),
                ('forsta_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flowise_questionnaire.routingedge')),
                ('question_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='flowise_questionnaire.questionmatch')),
            ],
            options={
                'db_table': 'flowise_routing_discrepancy',
                'ordering': ['-severity', 'created_at'],
            },
        ),
    ]
