# Generated by Django 6.0.5 on 2026-07-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0005_alter_normalizedquestion_question_type_questionmatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingedge',
            name='source_question',
            field=models.TextField(blank=True),
        ),
    ]
