# Generated by Django 6.0.5 on 2026-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0006_alter_routingedge_source_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdiscrepancy',
            name='discrepancy_type',
            field=models.CharField(choices=[('missing_in_forsta', 'Edge missing in Forsta+'), ('missing_in_colectica', 'Edge missing in Colectica'), ('condition_mismatch', 'Edge condition mismatch'), ('else_branch_only_in_forsta', 'Else-branch edge only in Forsta+')], max_length=40),
        ),
    ]
