# Generated by Django 6.0.5 on 2026-08-04 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0007_alter_routingdiscrepancy_discrepancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmatch',
            name='forsta_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flowise_questionnaire.questionnairemodule'),
        ),
    ]
