# Generated by Django 6.0.5 on 2026-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0008_questionmatch_forsta_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmatch',
            name='match_method',
            field=models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy'), ('name', 'Name'), ('manual', 'Manual')], default='fuzzy', max_length=20),
        ),
    ]
