# Generated by Django 6.0.5 on 2026-08-16 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0009_alter_questionmatch_match_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireVersionMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(choices=[('name', 'Name'), ('exact_text', 'Exact text'), ('fuzzy_text', 'Fuzzy text'), ('manual', 'Manual')], default='fuzzy_text', max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_version_matches', to='flowise_questionnaire.normalizedquestion')),
                ('compare_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flowise_questionnaire.questionnairemodule')),
                ('compare_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_version_matches', to='flowise_questionnaire.normalizedquestion')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flowise_questionnaire_version_match',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='VersionRoutingDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discrepancy_type', models.CharField(choices=[('missing_in_compare', 'Edge missing in compare module'), ('missing_in_base', 'Edge missing in base module')], max_length=40)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flowise_questionnaire.routingedge')),
                ('compare_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flowise_questionnaire.routingedge')),
                ('question_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='flowise_questionnaire.questionnaireversionmatch')),
            ],
            options={
                'db_table': 'flowise_version_routing_discrepancy',
                'ordering': ['-severity', 'created_at'],
            },
        ),
    ]
