# Generated by Django 6.0.5 on 2026-08-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowise_questionnaire', '0010_questionnaireversionmatch_versionroutingdiscrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionroutingdiscrepancy',
            name='discrepancy_type',
            field=models.CharField(choices=[('missing_in_compare', 'Edge missing in compare module'), ('missing_in_base', 'Edge missing in base module'), ('condition_mismatch', 'Edge condition text differs')], max_length=40),
        ),
    ]
