from __future__ import annotations

from dataclasses import dataclass, field, asdict
import re
from typing import Any, Dict, List, Optional, Set

from flowise_questionnaire.models import NormalizedQuestion, RoutingEdge
from flowise_questionnaire.services.condition_evaluator import evaluate_condition


@dataclass
class SimulationInput:
    """
    One deterministic simulation request.

    For now this represents one coverage intent:
    - seed_answers: answers generated by the deterministic coverage intent builder
    - required_external_context: external values needed by module routing
    - covers_edges: compact payload edge indexes this intent is meant to cover
    """

    id: str
    label: str
    seed_answers: Dict[str, Any] = field(default_factory=dict)
    required_external_context: Dict[str, Any] = field(default_factory=dict)
    covers_edges: List[int] = field(default_factory=list)
    condition_text: str = ""
    target_question: str = ""


@dataclass
class SimulationResult:
    """
    Result for one deterministic simulation.

    Step 16.4:
    - evaluates all conditional edges
    - separates target edges from non-target edges
    - reports coverage_status for the intended coverage edge(s)
    """

    intent_id: str
    intent_label: str
    inputs: Dict[str, Any] = field(default_factory=dict)

    active_questions: List[str] = field(default_factory=list)
    skipped_questions: List[str] = field(default_factory=list)

    triggered_edges: List[Dict[str, Any]] = field(default_factory=list)
    untriggered_edges: List[Dict[str, Any]] = field(default_factory=list)

    target_edges: List[Dict[str, Any]] = field(default_factory=list)
    non_target_edges: List[Dict[str, Any]] = field(default_factory=list)

    coverage_status: str = "unknown"
    coverage_summary: Dict[str, Any] = field(default_factory=dict)

    missing_inputs: List[str] = field(default_factory=list)
    invalid_inputs: List[str] = field(default_factory=list)

    warnings: List[str] = field(default_factory=list)


_CONDITION_IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_.]*\b")


def _normalize_input_key_map(inputs: Dict[str, Any]) -> Dict[str, str]:
    """
    Map lowercase input names to original input names.
    """

    return {str(key).lower(): str(key) for key in inputs.keys()}


def _get_question_names(module) -> set[str]:
    """
    Return known normalized question names for this module.
    """

    return set(
        NormalizedQuestion.objects.filter(module=module)
        .values_list("name", flat=True)
    )


def _get_conditional_edges(module):
    """
    Return conditional routing edges for this module.
    """

    return (
        RoutingEdge.objects.filter(module=module)
        .exclude(condition_text__isnull=True)
        .exclude(condition_text__exact="")
        .order_by("id")
    )


def _evaluation_get(evaluation: Any, key: str, default: Any = None) -> Any:
    """
    Read evaluator output from either:
    - dict-based result
    - dataclass/object-based result
    """

    if isinstance(evaluation, dict):
        return evaluation.get(key, default)

    return getattr(evaluation, key, default)


def _edge_value(edge: RoutingEdge, *field_names: str) -> Any:
    """
    Safely read the first existing/non-empty field from a RoutingEdge.
    """

    for field_name in field_names:
        value = getattr(edge, field_name, None)
        if value not in (None, ""):
            return value

    return None


def _edge_to_dict(
    *,
    edge: RoutingEdge,
    evaluation: Any,
    edge_index: int,
    is_target_edge: bool,
) -> Dict[str, Any]:
    """
    Convert a RoutingEdge + evaluation result into JSON-safe output.
    """

    return {
        "edge_index": edge_index,
        "edge_id": str(edge.id),
        "source": _edge_value(
            edge,
            "source_question",
            "source_question_name",
            "source_name",
            "from_question_name",
            "source",
        ),
        "target": _edge_value(
            edge,
            "target_question",
            "target_question_name",
            "target_name",
            "to_question_name",
            "target",
        ),
        "condition_text": getattr(edge, "condition_text", None),
        "evaluation_status": _evaluation_get(evaluation, "status"),
        "used_inputs": _evaluation_get(evaluation, "used_inputs", {}),
        "missing_inputs": _evaluation_get(evaluation, "missing_inputs", []),
        "normalized_expression": _evaluation_get(evaluation, "normalized_expression"),
        "warnings": _evaluation_get(evaluation, "warnings", []),
        "is_target_edge": is_target_edge,
    }


def _merge_inputs(simulation_input: SimulationInput) -> Dict[str, Any]:
    """
    Merge external context and seed answers.

    seed_answers intentionally wins if the same key appears in both places.
    """

    merged: Dict[str, Any] = {}
    merged.update(simulation_input.required_external_context or {})
    merged.update(simulation_input.seed_answers or {})
    return merged


def _extract_condition_identifiers(condition_text: str) -> List[str]:
    """
    Extract candidate variable names from a condition expression.

    This is only used to add case-compatible aliases before evaluation.
    """

    if not condition_text:
        return []

    ignored_words = {
        "if",
        "and",
        "or",
        "not",
        "true",
        "false",
    }

    identifiers: List[str] = []

    for match in _CONDITION_IDENTIFIER_RE.finditer(condition_text):
        token = match.group(0).strip()

        if not token:
            continue

        if token.lower() in ignored_words:
            continue

        identifiers.append(token)

    return identifiers


def _add_condition_case_aliases(
    *,
    inputs: Dict[str, Any],
    conditional_edges,
) -> Dict[str, Any]:
    """
    Add case-compatible aliases for variables referenced by conditions.

    Example:
        inputs contains AIDHH
        condition references AidHH

    The evaluator receives both:
        AIDHH and AidHH
    """

    aliased_inputs: Dict[str, Any] = dict(inputs)

    lower_to_existing_key: Dict[str, str] = {
        str(key).lower(): str(key)
        for key in inputs.keys()
    }

    for edge in conditional_edges:
        condition_text = getattr(edge, "condition_text", "") or ""

        for identifier in _extract_condition_identifiers(condition_text):
            lowered_identifier = identifier.lower()
            existing_key = lower_to_existing_key.get(lowered_identifier)

            if not existing_key:
                continue

            if identifier not in aliased_inputs:
                aliased_inputs[identifier] = inputs[existing_key]

    return aliased_inputs


def _normalize_missing_input_name(name: Any) -> str:
    """
    Normalize missing input names for display.
    """

    text = str(name).strip()

    if not text:
        return text

    return text.upper()


def _add_missing_input(
    *,
    missing_inputs_by_key: Dict[str, str],
    missing_name: Any,
) -> None:
    """
    Add one missing input using case-insensitive de-duplication.
    """

    normalized_name = _normalize_missing_input_name(missing_name)

    if not normalized_name:
        return

    dedupe_key = normalized_name.lower()

    if dedupe_key not in missing_inputs_by_key:
        missing_inputs_by_key[dedupe_key] = normalized_name


def _validate_input_names(
    *,
    inputs: Dict[str, Any],
    question_names: set[str],
    conditional_edges,
) -> List[str]:
    """
    Detect obviously invalid input names.

    For Step 16.4 this remains permissive.
    """

    invalid_inputs: List[str] = []
    known_lower = {name.lower() for name in question_names}
    input_key_map = _normalize_input_key_map(inputs)

    for lowered_key, original_key in input_key_map.items():
        if lowered_key in known_lower:
            continue

        if "." in original_key:
            continue

        # Keep permissive for now.
        # Some coverage intents contain helper or external variables.
        continue

    return invalid_inputs


def _normalize_covers_edges(covers_edges: Any) -> Set[int]:
    """
    Normalize raw covers_edges into a set of integer edge indexes.
    """

    normalized: Set[int] = set()

    if covers_edges is None:
        return normalized

    if not isinstance(covers_edges, list):
        covers_edges = [covers_edges]

    for value in covers_edges:
        try:
            normalized.add(int(value))
        except (TypeError, ValueError):
            continue

    return normalized


def _build_coverage_summary(
    *,
    target_edges: List[Dict[str, Any]],
    target_edge_indexes: Set[int],
) -> Dict[str, Any]:
    """
    Build a compact coverage summary for UI display.
    """

    triggered_target_edges = [
        edge for edge in target_edges
        if edge.get("evaluation_status") == "true"
    ]

    missing_target_edges = [
        edge for edge in target_edges
        if edge.get("evaluation_status") == "missing"
    ]

    false_target_edges = [
        edge for edge in target_edges
        if edge.get("evaluation_status") == "false"
    ]

    unknown_target_edges = [
        edge for edge in target_edges
        if edge.get("evaluation_status") not in {"true", "false", "missing"}
    ]

    return {
        "declared_target_edge_indexes": sorted(target_edge_indexes),
        "matched_target_edge_indexes": [
            edge.get("edge_index") for edge in target_edges
        ],
        "target_edge_count": len(target_edges),
        "triggered_target_edge_count": len(triggered_target_edges),
        "false_target_edge_count": len(false_target_edges),
        "missing_target_edge_count": len(missing_target_edges),
        "unknown_target_edge_count": len(unknown_target_edges),
        "triggered_target_edge_indexes": [
            edge.get("edge_index") for edge in triggered_target_edges
        ],
        "missing_target_edge_indexes": [
            edge.get("edge_index") for edge in missing_target_edges
        ],
        "false_target_edge_indexes": [
            edge.get("edge_index") for edge in false_target_edges
        ],
    }


def _determine_coverage_status(
    *,
    target_edges: List[Dict[str, Any]],
    target_edge_indexes: Set[int],
) -> str:
    """
    Determine whether the coverage intent succeeded.

    Status values:
    - no_target_edges: intent did not declare covers_edges
    - target_edge_not_found: covers_edges did not match available edge indexes
    - covered: at least one intended target edge evaluated true
    - blocked_missing_inputs: at least one target edge could not evaluate due to missing inputs
    - not_covered: target edge(s) evaluated but none were true
    - unknown: unexpected evaluator status
    """

    if not target_edge_indexes:
        return "no_target_edges"

    if not target_edges:
        return "target_edge_not_found"

    statuses = {
        str(edge.get("evaluation_status"))
        for edge in target_edges
    }

    if "true" in statuses:
        return "covered"

    if "missing" in statuses:
        return "blocked_missing_inputs"

    if statuses and statuses.issubset({"false"}):
        return "not_covered"

    return "unknown"


def simulate_coverage_intent(
    *,
    module,
    simulation_input: SimulationInput,
) -> SimulationResult:
    """
    Simulate one coverage intent.

    Step 16.4 behavior:
    - load conditional edges
    - evaluate each edge condition against merged inputs
    - populate triggered_edges / untriggered_edges / missing_inputs / warnings
    - split target_edges from non_target_edges using covers_edges
    - compute coverage_status
    - do not yet compute active/skipped questions
    """

    inputs = _merge_inputs(simulation_input)

    result = SimulationResult(
        intent_id=simulation_input.id,
        intent_label=simulation_input.label,
        inputs=inputs,
    )

    question_names = _get_question_names(module)
    conditional_edges = list(_get_conditional_edges(module))
    target_edge_indexes = _normalize_covers_edges(simulation_input.covers_edges)

    target_condition_text = _normalize_condition_text(
        simulation_input.condition_text
    )

    target_question_name = _normalize_question_name(
        simulation_input.target_question
    )

    inputs = _add_condition_case_aliases(
        inputs=inputs,
        conditional_edges=conditional_edges,
    )

    result.inputs = inputs

    result.invalid_inputs = _validate_input_names(
        inputs=inputs,
        question_names=question_names,
        conditional_edges=conditional_edges,
    )

    missing_inputs_by_key: Dict[str, str] = {}

    for edge_index, edge in enumerate(conditional_edges):
        condition_text = getattr(edge, "condition_text", None)

        if not condition_text:
            continue

        edge_condition_text = _normalize_condition_text(
            getattr(edge, "condition_text", None)
        )

        edge_target_question = _normalize_question_name(
            getattr(edge, "target_question", None)
        )

        condition_matches = (
                bool(target_condition_text)
                and edge_condition_text == target_condition_text
        )

        target_matches = (
                not target_question_name
                or edge_target_question == target_question_name
        )

        is_target_edge = condition_matches and target_matches

        try:
            evaluation = evaluate_condition(
                condition_text=condition_text,
                inputs=inputs,
            )
        except TypeError:
            evaluation = evaluate_condition(condition_text, inputs)

        edge_payload = _edge_to_dict(
            edge=edge,
            evaluation=evaluation,
            edge_index=edge_index,
            is_target_edge=is_target_edge,
        )

        evaluation_status = _evaluation_get(evaluation, "status", "unknown")
        evaluation_missing_inputs = _evaluation_get(evaluation, "missing_inputs", [])
        evaluation_warnings = _evaluation_get(evaluation, "warnings", [])

        for missing_name in evaluation_missing_inputs:
            _add_missing_input(
                missing_inputs_by_key=missing_inputs_by_key,
                missing_name=missing_name,
            )

        for warning in evaluation_warnings:
            result.warnings.append(
                f"Edge index {edge_index} ({edge.id}): {warning}"
            )

        if evaluation_status == "true":
            result.triggered_edges.append(edge_payload)
        elif evaluation_status == "false":
            result.untriggered_edges.append(edge_payload)
        elif evaluation_status == "missing":
            result.untriggered_edges.append(edge_payload)
            result.warnings.append(
                f"Edge index {edge_index} ({edge.id}): condition could not be evaluated because inputs are missing."
            )
        else:
            result.untriggered_edges.append(edge_payload)
            result.warnings.append(
                f"Edge index {edge_index} ({edge.id}): unsupported evaluator status '{evaluation_status}'."
            )

        if is_target_edge:
            result.target_edges.append(edge_payload)
        else:
            result.non_target_edges.append(edge_payload)

    result.missing_inputs = sorted(missing_inputs_by_key.values())

    result.coverage_status = _determine_coverage_status(
        target_edges=result.target_edges,
        target_edge_indexes=target_edge_indexes,
    )

    result.coverage_summary = _build_coverage_summary(
        target_edges=result.target_edges,
        target_edge_indexes=target_edge_indexes,
    )

    result.warnings.append(
        "Step 16.4 evaluates all conditional edges globally and separately reports target edge coverage. Active/skipped question traversal is not implemented yet."
    )

    return result


def simulate_all_coverage_intents_for_module(
    *,
    module,
    coverage_intents: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Run Step 16.4 simulation for every deterministic coverage intent.
    """

    results: List[Dict[str, Any]] = []

    for raw_intent in coverage_intents:
        simulation_input = SimulationInput(
            id=str(
                raw_intent.get("id")
                or raw_intent.get("name")
                or raw_intent.get("purpose")
                or "unnamed_intent"
            ),
            label=str(
                raw_intent.get("label")
                or raw_intent.get("name")
                or raw_intent.get("description")
                or raw_intent.get("id")
                or "Unnamed coverage intent"
            ),
            seed_answers=raw_intent.get("seed_answers") or {},
            required_external_context=raw_intent.get("required_external_context") or {},
            covers_edges=raw_intent.get("covers_edges") or [],
            condition_text=str(raw_intent.get("condition_text") or ""),
            target_question=str(raw_intent.get("target_question") or ""),
        )

        result = simulate_coverage_intent(
            module=module,
            simulation_input=simulation_input,
        )

        results.append(asdict(result))

    return results


def _normalize_condition_text(condition_text: Any) -> str:
    """
    Normalize condition text for target-edge matching.
    """

    text = str(condition_text or "").strip()

    # Collapse repeated whitespace.
    text = re.sub(r"\s+", " ", text)

    return text.lower()


def _normalize_question_name(value: Any) -> str:
    """
    Normalize question names for matching simulator coverage targets.
    """

    return str(value or "").strip().lower()